Repository k-twitter/Ktwitter-backend, pull requests merged in 2023-08, with the labels that each got.

#4 #1 [FEATURE] Profile 도메인 CRUD 구현
  sns_service/build.gradle.kts
  sns_service/docker-compose.yaml
  sns_service/src/main/kotlin/joryu/sns_service/common/dto/response/CommonResponseBody.kt
  sns_service/src/main/kotlin/joryu/sns_service/profile/controller/ProfileApiController.kt
  sns_service/src/main/kotlin/joryu/sns_service/profile/dto/request/ProfileCreateRequest.kt
  sns_service/src/main/kotlin/joryu/sns_service/profile/dto/request/ProfileUpdateRequest.kt
  sns_service/src/main/kotlin/joryu/sns_service/profile/dto/response/ProfileInfoResponse.kt
  sns_service/src/main/kotlin/joryu/sns_service/profile/entity/Profile.kt
  sns_service/src/main/kotlin/joryu/sns_service/profile/exception/ProfileBaseException.kt
  sns_service/src/main/kotlin/joryu/sns_service/profile/exception/ProfileExceptionEnums.kt
  sns_service/src/main/kotlin/joryu/sns_service/profile/exception/ProfileExceptionHandler.kt
  sns_service/src/main/kotlin/joryu/sns_service/profile/repository/ProfileRepository.kt
  sns_service/src/main/kotlin/joryu/sns_service/profile/service/ProfileService.kt
  sns_service/src/main/resources/application.properties
  sns_service/src/main/resources/application.yaml
Labels: feature

#17 fix: X protocol 문제 때문에 33060 -> 33061 포트로 변경
  sns_service/docker-compose.yaml
  sns_service/src/main/resources/application.yaml
Labels: bug

#18 feat: baseEntity 생성 & FeedEntity 골격만 생성
  sns_service/src/main/kotlin/joryu/sns_service/SnsServiceApplication.kt
  sns_service/src/main/kotlin/joryu/sns_service/feed/entity/Feed.kt
  sns_service/src/main/kotlin/joryu/sns_service/feed/repository/FeedRepository.kt
  sns_service/src/main/kotlin/joryu/sns_service/profile/entity/BaseEntity.kt
  sns_service/src/test/kotlin/joryu/sns_service/feed/entity/FeedEntityTest.kt
Labels: feature

#9 #5 [팔로우] 기본 베이스 기능 구현
  sns_service/src/main/kotlin/joryu/sns_service/follower/controller/FollowerController.kt
  sns_service/src/main/kotlin/joryu/sns_service/follower/dto/request/FollowRequest.kt
  sns_service/src/main/kotlin/joryu/sns_service/follower/dto/request/UnFollowRequest.kt
  sns_service/src/main/kotlin/joryu/sns_service/follower/dto/response/AllFollowingProfilesResponse.kt
  sns_service/src/main/kotlin/joryu/sns_service/follower/entity/Follower.kt
  sns_service/src/main/kotlin/joryu/sns_service/follower/repository/FollowerRepository.kt
  sns_service/src/main/kotlin/joryu/sns_service/follower/service/FollowerService.kt
  sns_service/src/main/kotlin/joryu/sns_service/profile/controller/ProfileApiController.kt
  sns_service/src/main/kotlin/joryu/sns_service/profile/dto/request/ProfileCreateRequest.kt
  sns_service/src/main/kotlin/joryu/sns_service/profile/dto/request/ProfileUpdateRequest.kt
  sns_service/src/main/kotlin/joryu/sns_service/profile/dto/response/ProfileInfoResponse.kt
  sns_service/src/main/kotlin/joryu/sns_service/profile/entity/Profile.kt
  sns_service/src/main/kotlin/joryu/sns_service/profile/service/ProfileService.kt
Labels: feature, refactor, chore
